### PR TITLE
Remove broken JS jobs link

### PR DESCRIPTION
**Pull request by lookfirst**
If someone knows the new link...

### CODE REVIEW

**Comment by sluongng** [comment]
I just wana note that the Scala community in the provided link seems quite dead. Should be removed.

**Comment by pierreneter** [comment]
@sluongng i have a `pull request`: #560, but, noone cares. So,... i just closed it. Lol. 😆 I think the maintainers of this repo don't like changes from us. Let's they change it for their seft.

**Comment by pierreneter** [comment]
@lookfirst Wow, you have a nice account 😍, first commit from 2006... but, I still find it quite curious that the first commit of github was from 2007. https://github.com/about lol. It is interesting.

**Comment by trexnix** [comment]
@pierreneter The first commit in Git (which was first released in 2005) != The first commit was pushed to Github.

**Comment by lookfirst** [comment]
@pierreneter @trexnix is right. That is a project that was migrated from code.google.com when it shut down. 

That said, I've been on the internet since 1991 (and coding since the 1980's), so 2006 is nothing. 🥇 

Kids these days... think they know everything. ha! 👍

**Comment by huytd** [comment]
@lookfirst Thanks for the pull request.

The JavaScript Vietnam community now moved to #javascript channel of Ruby Vietnam Slack as well, could you update your pull request to reflect that change?

-Huy

**Comment by huytd** [comment]
Well, actually, we can use the Facebook URL: https://www.facebook.com/vietnam.javascript

**Comment by pierreneter** [comment]
@lookfirst i'm just saying it is interesting. i know Git was created in 2005. I just like your work, it from 2006, before github was born. I don't want there to be any misunderstanding here. Thanks.

**Comment by pierreneter** [comment]
Olds these days.. think they understand everyone. 👍

**Comment by lookfirst** [comment]
@huytd - Point at a Group that people can join instead of just a Page? Seems better no?

@pierreneter - LOL... I know you're kidding but ... yea... I don't pretend to understand anyone. 🌮

**Comment by pierreneter** [comment]
@lookfirst Please ignore me, I just say some silly things, like you. 😆

**Comment by qcam** [comment]
@lookfirst @pierreneter thanks for the PRs and sorry for missing yours @pierreneter.

As mentioned by @huytd, Javascript Vietnam and C++ Vietnam have respectively moved to [`#javascript` https://vietnamrb.slack.com/messages/C0J7M3P8V/](https://vietnamrb.slack.com/messages/C0J7M3P8V/) and [`#cpp` https://vietnamrb.slack.com/messages/C0Y25HCGL/](https://vietnamrb.slack.com/messages/C0Y25HCGL/) in Ruby Vietnam Slack group. Could you please update the PR?

**Comment by qcam** [comment]
Fixed via https://github.com/awesome-jobs/vietnam/commit/6f254a34d00157f07850ce636a4dafbbaf5fda22

**Pull request closed without merging**
